### ISSUE TITLE
Chapter 8: error on ecommerce app

### ISSUE THREAD

**Issue by carloscrovara** [PacktPublishing/React-Native-Blueprints#4]
I have an issue with the ecommerce app (chapter 8): 

On the Android app the button of "Confirm purchase" didn´t work.

**Comment by emilioicai** [comment]
@carloscrovara can you provide more information please? I cannot reproduce in my local environment

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue. If the issue still persists, feel free to reopen it.
Thanks!
