### ISSUE TITLE
Repo is categorized as 'Objective C' not 'JavaScript' 

### ISSUE THREAD

**Issue by sanbeaman** [PacktPublishing/React-Native-Blueprints#5]
I have been working thru this book thru the  packtpub mapt subscription.
The repo author and book author are different and since it was classified as 'Objective C' i passed it took me multiple attempts to find the code.

thanks
drew

**Comment by emilioicai** [comment]
Where do you see it's classified as 'Objective C'?

**Comment by sohamapackt** [comment]
Hi,

I am closing this issue. If the issue still persists, feel free to reopen it.
Thanks!
