### ISSUE TITLE
 on ecommerce app api

### ISSUE THREAD

**Issue by pherm** [PacktPublishing/React-Native-Blueprints#6]
Can you provide a real backend api example? I don't understand how to set it in production! Ps. Compliments for your book, written well and clear!

**Comment by emilioicai** [comment]
@pherm For the ecommerce chapter we provided a mockup API to simplify the codebase (`/src/api.js`).

If you want to learn about how to setup a backend, please take a look at chapter 6. It should be really simple to apply the backend knowledge from chapter 6 into the e-commerce app by replacing the API calls done in `/src/api.js`.
